import { MasterRoutineItem, DaySchedule, DayOfWeek, TaskItem, BreakItem } from '../types/schedule';

export const INITIAL_MASTER_ROUTINES: MasterRoutineItem[] = [
  {
    id: 'master-sleep',
    title: 'Sleep & Night Recovery',
    type: 'break',
    startTime: '23:00',
    endTime: '07:00',
    durationMinutes: 480,
    category: 'Rest',
    description: 'Non-negotiable restorative sleep block for mental clarity and physical recovery.',
    recurrence: 'daily',
  },
  {
    id: 'master-morning',
    title: 'Morning Routine & Hydration',
    type: 'task',
    startTime: '07:00',
    endTime: '08:00',
    durationMinutes: 60,
    category: 'Health',
    priority: 'medium',
    description: 'Hydration, light stretching, and preparing for the day ahead.',
    recurrence: 'daily',
  },
  {
    id: 'master-lunch',
    title: 'Lunch & Screen-Free Break',
    type: 'break',
    startTime: '12:30',
    endTime: '13:30',
    durationMinutes: 60,
    category: 'Rest',
    description: 'Nutritious meal and offline relaxation away from monitors.',
    recurrence: 'daily',
  },
  {
    id: 'master-review',
    title: 'Daily Review & Logbook',
    type: 'task',
    startTime: '22:30',
    endTime: '23:00',
    durationMinutes: 30,
    category: 'Personal',
    priority: 'low',
    description: 'Review day outcomes, log accomplishments, and finalize tomorrow priorities.',
    recurrence: 'daily',
  },
];

const now = Date.now();

export const INITIAL_DAY_SCHEDULES: Record<DayOfWeek, DaySchedule> = {
  mon: {
    day: 'mon',
    excludedMasterIds: [],
    overrides: {},
    customItems: [
      {
        id: 'mon-task-1',
        title: 'Architecture Review & System Schema',
        type: 'task',
        priority: 'high',
        isCompleted: true,
        startTime: '09:00',
        endTime: '11:30',
        durationMinutes: 150,
        category: 'Work',
        description: 'Finalize Section 7 TypeScript data contracts and review state synchronization patterns.',
        createdAt: now - 3600000 * 5,
        updatedAt: now - 3600000 * 2,
      } as TaskItem,
      {
        id: 'mon-task-2',
        title: 'Sprint Planning & Backlog Grooming',
        type: 'task',
        priority: 'medium',
        isCompleted: false,
        startTime: '11:30',
        endTime: '12:30',
        durationMinutes: 60,
        category: 'Work',
        description: 'Coordinate deliverables with team and assign milestone blockers.',
        createdAt: now - 3600000 * 4,
        updatedAt: now - 3600000 * 4,
      } as TaskItem,
      {
        id: 'mon-task-3',
        title: 'Deep Work: Core Engine Implementation',
        type: 'task',
        priority: 'high',
        isCompleted: false,
        startTime: '14:00',
        endTime: '17:00',
        durationMinutes: 180,
        category: 'Work',
        description: 'Build overlap collision logic and 1,440-minute day budget calculators.',
        createdAt: now - 3600000 * 3,
        updatedAt: now - 3600000 * 3,
      } as TaskItem,
      {
        id: 'mon-break-1',
        title: 'Outdoor Run / Calisthenics',
        type: 'break',
        startTime: '17:30',
        endTime: '18:30',
        durationMinutes: 60,
        category: 'Health',
        description: 'Aerobic exercise and sunlight exposure.',
      } as BreakItem,
      {
        id: 'mon-task-4',
        title: 'Code Review & PR Merges',
        type: 'task',
        priority: 'medium',
        isCompleted: false,
        startTime: '19:30',
        endTime: '20:30',
        durationMinutes: 60,
        category: 'Work',
        description: 'Inspect open pull requests and verify automated test suites.',
        createdAt: now - 3600000 * 2,
        updatedAt: now - 3600000 * 2,
      } as TaskItem,
    ],
  },
  tue: {
    day: 'tue',
    excludedMasterIds: [],
    overrides: {},
    customItems: [
      {
        id: 'tue-task-1',
        title: 'UI Design System Token Audit',
        type: 'task',
        priority: 'high',
        isCompleted: false,
        startTime: '09:00',
        endTime: '12:00',
        durationMinutes: 180,
        category: 'Work',
        description: 'Map Vercel-inspired typography scales, stacked elevation shadows, and hairline borders.',
        createdAt: now,
        updatedAt: now,
      } as TaskItem,
      {
        id: 'tue-task-2',
        title: 'Zustand Store & IndexedDB Sync',
        type: 'task',
        priority: 'medium',
        isCompleted: false,
        startTime: '14:00',
        endTime: '16:30',
        durationMinutes: 150,
        category: 'Work',
        description: 'Implement asynchronous offline persistence via idb-keyval.',
        createdAt: now,
        updatedAt: now,
      } as TaskItem,
      {
        id: 'tue-break-1',
        title: 'Strength Training Session',
        type: 'break',
        startTime: '17:30',
        endTime: '18:45',
        durationMinutes: 75,
        category: 'Health',
        description: 'Upper body resistance training session.',
      } as BreakItem,
      {
        id: 'tue-task-3',
        title: 'Technical Reading: Distributed Systems',
        type: 'task',
        priority: 'low',
        isCompleted: false,
        startTime: '20:00',
        endTime: '21:30',
        durationMinutes: 90,
        category: 'Learning',
        description: 'Read 2 chapters on consensus algorithms and conflict resolution.',
        createdAt: now,
        updatedAt: now,
      } as TaskItem,
    ],
  },
  wed: {
    day: 'wed',
    excludedMasterIds: [],
    overrides: {},
    customItems: [
      {
        id: 'wed-task-1',
        title: 'Timeline View Component Scaffolding',
        type: 'task',
        priority: 'high',
        isCompleted: false,
        startTime: '08:30',
        endTime: '11:30',
        durationMinutes: 180,
        category: 'Work',
        description: 'Create chronological timeline feed and interactive expandable task cards.',
        createdAt: now,
        updatedAt: now,
      } as TaskItem,
      {
        id: 'wed-task-2',
        title: 'Design Review with Stakeholders',
        type: 'task',
        priority: 'medium',
        isCompleted: false,
        startTime: '14:00',
        endTime: '15:30',
        durationMinutes: 90,
        category: 'Work',
        description: 'Walkthrough visual design tokens and 24-hour budgeting feedback.',
        createdAt: now,
        updatedAt: now,
      } as TaskItem,
      {
        id: 'wed-break-1',
        title: 'Afternoon Walk & Coffee',
        type: 'break',
        startTime: '16:00',
        endTime: '16:45',
        durationMinutes: 45,
        category: 'Rest',
        description: 'Quick coffee walk and fresh air.',
      } as BreakItem,
    ],
  },
  thu: {
    day: 'thu',
    excludedMasterIds: [],
    overrides: {},
    customItems: [
      {
        id: 'thu-task-1',
        title: 'Collision Detection Visual Indicator',
        type: 'task',
        priority: 'high',
        isCompleted: false,
        startTime: '09:00',
        endTime: '12:00',
        durationMinutes: 180,
        category: 'Work',
        description: 'Highlight overlapping entries with subtle warning borders and minute badges.',
        createdAt: now,
        updatedAt: now,
      } as TaskItem,
      {
        id: 'thu-task-2',
        title: 'Free Slot Gap Filler Component',
        type: 'task',
        priority: 'medium',
        isCompleted: false,
        startTime: '14:00',
        endTime: '16:30',
        durationMinutes: 150,
        category: 'Work',
        description: 'Implement dashed clickable empty slot cards that launch pre-populated add dialog.',
        createdAt: now,
        updatedAt: now,
      } as TaskItem,
    ],
  },
  fri: {
    day: 'fri',
    excludedMasterIds: [],
    overrides: {},
    customItems: [
      {
        id: 'fri-task-1',
        title: 'Weekly Retro & Metric Analytics',
        type: 'task',
        priority: 'high',
        isCompleted: false,
        startTime: '09:00',
        endTime: '11:00',
        durationMinutes: 120,
        category: 'Work',
        description: 'Calculate Work-to-Rest ratio and weekly completion velocity.',
        createdAt: now,
        updatedAt: now,
      } as TaskItem,
      {
        id: 'fri-task-2',
        title: 'Release Preparation & Documentation',
        type: 'task',
        priority: 'medium',
        isCompleted: false,
        startTime: '14:00',
        endTime: '16:30',
        durationMinutes: 150,
        category: 'Work',
        description: 'Prepare single-file standalone bundle and release notes.',
        createdAt: now,
        updatedAt: now,
      } as TaskItem,
      {
        id: 'fri-break-1',
        title: 'Team Social & Downtime',
        type: 'break',
        startTime: '17:00',
        endTime: '18:30',
        durationMinutes: 90,
        category: 'Personal',
        description: 'End of week celebration with colleagues.',
      } as BreakItem,
    ],
  },
  sat: {
    day: 'sat',
    excludedMasterIds: [],
    overrides: {},
    customItems: [
      {
        id: 'sat-break-1',
        title: 'Nature Hike & Photography',
        type: 'break',
        startTime: '08:30',
        endTime: '12:00',
        durationMinutes: 210,
        category: 'Health',
        description: 'Trail hiking and outdoor nature photography.',
      } as BreakItem,
      {
        id: 'sat-task-1',
        title: 'Personal Creative Project',
        type: 'task',
        priority: 'medium',
        isCompleted: false,
        startTime: '14:00',
        endTime: '17:00',
        durationMinutes: 180,
        category: 'Learning',
        description: 'Experiment with creative coding and generative shaders.',
        createdAt: now,
        updatedAt: now,
      } as TaskItem,
    ],
  },
  sun: {
    day: 'sun',
    excludedMasterIds: [],
    overrides: {},
    customItems: [
      {
        id: 'sun-break-1',
        title: 'Brunch & Family Time',
        type: 'break',
        startTime: '10:00',
        endTime: '12:30',
        durationMinutes: 150,
        category: 'Personal',
        description: 'Slow morning brunch and quality family conversation.',
      } as BreakItem,
      {
        id: 'sun-task-1',
        title: 'Weekly Planning & Goal Setting',
        type: 'task',
        priority: 'high',
        isCompleted: false,
        startTime: '17:00',
        endTime: '18:30',
        durationMinutes: 90,
        category: 'Personal',
        description: 'Audit priorities for upcoming week and prepare time allocations.',
        createdAt: now,
        updatedAt: now,
      } as TaskItem,
    ],
  },
};
